function h=show(h)
    if isvalid(h.f)
        return
    end
    %figure;
    h.f = figure('Visible','on','Units','normalized',...
                    'Position',[0.01,0.01,0.7,0.9],...
                    'MenuBar','figure','toolBar','figure',...
                    'DeleteFcn',@(~,~)Delete_f_Callback(h));
    colormap(gray(256));
    h.b_axes = axes('Units','normalized',...
                   'Position',[0.03,0.3,0.6,0.65]);
    h.p_axes = axes('Units','normalized',...
                   'Position',[0.65,0.05,0.3,0.45]);
    
    %uicontrol
    h.b_play = uicontrol('Style','pushbutton','Units','normalized',...
        'String','play','Position',[0.05,0.2,0.1,0.05],'FontSize',15,...
        'Callback',@(~,~)play_btn_Callback(h));
    h.b_stop = uicontrol('Style','pushbutton','Units','normalized',...
        'String','stop','Position',[0.15,0.2,0.1,0.05],'FontSize',15,...
        'Callback',@(~,~)stop_btn_Callback(h));
    uicontrol('Style','text','Units','normalized',...
        'String','Curr Frame:','Position',[0.25,0.2,0.1,0.05],'FontSize',15);
    h.b_curr_frame = uicontrol('Style','edit','Units','normalized',...
        'String','1','Position',[0.35,0.2,0.1,0.05],'FontSize',15,...
        'Callback',@(~,~)curr_Frame_Callback(h));
    uicontrol('Style','text','Units','normalized',...
        'String','fps(frame/s):','Position',[0.50,0.2,0.1,0.05],'FontSize',15);
    h.fps=uicontrol('Style','edit','Units','normalized',...
        'String','10','Position',[0.50,0.15,0.1,0.05],'FontSize',15);
    h.b_disp_line = uicontrol('Style','checkbox','Units','normalized',...
        'String','if display tracking res?','Position',[0.05,0.15,0.2,0.05],'FontSize',15,'Value',true);
    h.b_draw_line = uicontrol('Style','pushbutton','Units','normalized',...
        'String','draw a line','Position',[0.05,0.1,0.1,0.05],'FontSize',15,...
    'Callback',@(~,~)draw_line_Callback(h));
    uicontrol('Style','text','Units','normalized',...
        'String','Width:','Position',[0.15,0.1,0.1,0.05],'FontSize',15);
    h.b_width=uicontrol('Style','edit','Units','normalized',...
        'String','6','Position',[0.25,0.1,0.1,0.05],'FontSize',15);
    
    h.b_track = uicontrol('Style','pushbutton','Units','normalized',...
        'String','save','Position',[0.05,0.05,0.1,0.05],'FontSize',15,...
        'Callback',@(~,~)save_gf_btn_Callback(h));
    h.b_track = uicontrol('Style','pushbutton','Units','normalized',...
        'String','track','Position',[0.75,0.95,0.15,0.05],'FontSize',15,...
        'Callback',@(~,~)track_btn_Callback(h));
    h.ifparallel = uicontrol('Style','checkbox','Units','normalized',...
        'String','if parallel','Position',[0.65,0.95,0.1,0.05],'FontSize',15);
    h.delete_gf = uicontrol('Style','pushbutton','Units','normalized',...
        'String','delete GF:','Position',[0.05,0,0.1,0.05],'FontSize',15,...
        'Callback',@(~,~)delete_gf_Callback(h));
    h.gf_to_be_delete = uicontrol('Style','edit','Units','normalized',...
        'Position',[0.15,0,0.1,0.05],'FontSize',15);
    h.b_board=uicontrol('Style','text','Units','normalized',...
        'String','The position of the new fiber is:','Position',[0.35,0,0.2,0.15],'FontSize',15);
    %
    h.vdlist=uicontrol('Style','popupmenu','Units','normalized',...
        'String',{''},'Position',[0.75,0.8,0.15,0.05],'FontSize',15,...
        'Callback',@(~,~)vdlist_Callback(h));
    h=vdlist_Callback(h);
    
    h.openfile=uicontrol('Style','pushbutton','Units','normalized',...
        'String',{'open avi'},'Position',[0.75,0.85,0.15,0.05],'FontSize',15,...
        'Callback',@(~,~)openfile_Callback(h));
    h.savefile=uicontrol('Style','pushbutton','Units','normalized',...
        'String',{'save Result'},'Position',[0.75,0.75,0.15,0.05],'FontSize',15,...
        'Callback',@(~,~)savefile_Callback(h));
    h.open_res=uicontrol('Style','pushbutton','Units','normalized',...
        'String',{'open Result'},'Position',[0.75,0.70,0.15,0.05],'FontSize',15,...
        'Callback',@(~,~)open_res_Callback(h));
    h.export_txt=uicontrol('Style','pushbutton','Units','normalized',...
        'String',{'export txt'},'Position',[0.75,0.65,0.15,0.05],'FontSize',15,...
        'Callback',@(~,~)export_txt_Callback(h));
    h.update_disp_info=uicontrol('Style','pushbutton','Units','normalized',...
        'String',{'update_disp_info'},'Position',[0.75,0.60,0.15,0.05],'FontSize',15,...
        'Callback',@(~,~)update_disp_info_Callback(h));
    h.plot_res=uicontrol('Style','pushbutton','Units','normalized',...
        'String',{'plot_res'},'Position',[0.75,0.55,0.15,0.05],'FontSize',15,...
        'Callback',@(~,~)plot_res_Callback(h));
       %
    h.Plot_gf_res=uicontrol('Style','edit','Units','normalized',...
        'String',' ','Position',[0.25,0.05,0.1,0.05],'FontSize',15,...
        'Callback',@(~,~)Plot_gf_result_Callback(h));
    h.gf_n_to_be_plot=uicontrol('Style','text','Units','normalized',...
        'String','Plot GF:','Position',[0.15,0.05,0.1,0.05],'FontSize',15);
    h.Frame_num_tobe_cut=uicontrol('Style','edit','Units','normalized',...
        'String',' ','Position',[0.35,0.00,0.1,0.05],'FontSize',15);
    h.cut_Framenum=uicontrol('Style','pushbutton','Units','normalized',...
        'String',{'Cut Frame:'},'Position',[0.25,0.00,0.1,0.05],'FontSize',15,...
        'Callback',@(~,~)cut_Framenum_Callback(h));
    h.open_folder=uicontrol('Style','pushbutton','Units','normalized',...
        'String',{'open folder'},'Position',[0.75,0.90,0.15,0.05],'FontSize',15,...
        'Callback',@(~,~)open_folder_Callback(h));
end
